version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 23.3.0
      python: 3.12
    commands:
      - echo "Installing dependencies for backend and frontend"
  pre_build: 
    commands:
      - echo "Installing dependencies for backend"
      - cd Backend
      - cd s3Trigger
      - pip install -r requirements.txt -t .
      - cd ..
      - cd ..
      - echo "Installing dependencies for frontend"
      - cd Frontend
      - cd image-processing
      - npm install
      - cd ..
      - cd ..
  build:
    commands:
      - echo "Building backend"
      - cd Backend
      - cd s3Trigger
      - zip -r lambda_package.zip .
      - ls -l
      - echo "Zip Successfully Created"
      - cd ..
      - cd ..
      - echo "Building frontend"
      - cd Frontend
      - cd image-processing
      - npm run build
      - cd ..
      - cd ..

post_build:
  commands:
    - aws lambda update-function-code --function-name s3Trigger --zip-file fileb://lambda_package.zip
    - aws s3 cp Frontend/image-processing/build s3://react-build-image-processing/ --recursive
artifacts:
  files:
    - Backend/s3Trigger/lambda_package.zip
    - Frontend/image-processing/build
